name: Publish to ECR
description: Build a container image and Pushes it to ECR

inputs:
  folder:
    required: true
    type: string
  repository_name:
    required: true
    type: string
  image_tag: 
    required: true
    type: string
  aws_region:
    required: true
    type: string
  iam_role:
    required: true

permissions:
      id-token: write
      contents: read

runs:
  using: composite
  steps:
  - name: Configure AWS Credentials
    uses: aws-actions/configure-aws-credentials@v1
    with:
      role-to-assume: ${{inputs.iam_role}}
      aws-region: ${{inputs.aws_region}}
#       role-skip-session-tagging: true
#       role-duration-seconds: 1200

  - name: Login to ECR
    id: login-ecr
    uses: aws-actions/amazon-ecr-login@v1

  - name: Build and Push image to ECR
    shell: bash
    env:
      REGISTRY: ${{steps.login-ecr.outputs.registry}}
      REPOSITORY: ${{inputs.repository_name}}
      IMAGE_TAG: ${{inputs.image_tag}}
    run: |
      cd ${{inputs.folder}}
      docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
      echo "Pushing image to ECR..."
      docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
